// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CosmereContext))]
    [Migration("20260407222403_SeedAnguilaAerea")]
    partial class SeedAnguilaAerea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Messages.Database.Entities.ArmorCatalogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ArmorTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Desvio")
                        .HasColumnType("integer");

                    b.Property<List<int>>("ExpertTraitIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<int>>("TraitIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("ArmorCatalog");
                });

            modelBuilder.Entity("Messages.Database.Entities.CampaignEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GmUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("InviteActive")
                        .HasColumnType("boolean");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GmUserId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Messages.Database.Entities.CampaignMemberEntity", b =>
                {
                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CampaignId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CampaignMembers");
                });

            modelBuilder.Entity("Messages.Database.Entities.CatalogOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("CatalogOptions");
                });

            modelBuilder.Entity("Messages.Database.Entities.CharacterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Agilidad")
                        .HasColumnType("integer");

                    b.Property<string>("Apariencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArmasLigeras")
                        .HasColumnType("integer");

                    b.Property<int>("ArmasPesadas")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Armor")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Ascendencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Atletismo")
                        .HasColumnType("integer");

                    b.Property<string>("CaminoHeroico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaminoRadiante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<int>("Concentration")
                        .HasColumnType("integer");

                    b.Property<string>("Conexiones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Conocimiento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deduccion")
                        .HasColumnType("integer");

                    b.Property<int>("Desvio")
                        .HasColumnType("integer");

                    b.Property<int>("Discernimiento")
                        .HasColumnType("integer");

                    b.Property<int>("Disciplina")
                        .HasColumnType("integer");

                    b.Property<int>("Engano")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Equipment")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Fuerza")
                        .HasColumnType("integer");

                    b.Property<string>("HabilidadPersonalizada1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HabilidadPersonalizada1Atributo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HabilidadPersonalizada1Valor")
                        .HasColumnType("integer");

                    b.Property<string>("HabilidadPersonalizada2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HabilidadPersonalizada2Atributo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HabilidadPersonalizada2Valor")
                        .HasColumnType("integer");

                    b.Property<string>("HabilidadPersonalizada3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HabilidadPersonalizada3Atributo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HabilidadPersonalizada3Valor")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Hurto")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Intelecto")
                        .HasColumnType("integer");

                    b.Property<int>("Intimidacion")
                        .HasColumnType("integer");

                    b.Property<int>("Investiture")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNpc")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleToPlayers")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Liderazgo")
                        .HasColumnType("integer");

                    b.Property<int>("Manufactura")
                        .HasColumnType("integer");

                    b.Property<int>("MarcosInfusas")
                        .HasColumnType("integer");

                    b.Property<int>("MarcosOpacas")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConcentration")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxInvestiture")
                        .HasColumnType("integer");

                    b.Property<int>("Medicina")
                        .HasColumnType("integer");

                    b.Property<string>("Metas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Obstaculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Percepcion")
                        .HasColumnType("integer");

                    b.Property<int>("Perspicacia")
                        .HasColumnType("integer");

                    b.Property<int>("Persuasion")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Presencia")
                        .HasColumnType("integer");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sigilo")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Spells")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Supervivencia")
                        .HasColumnType("integer");

                    b.Property<string>("Talentos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Velocidad")
                        .HasColumnType("integer");

                    b.Property<int>("Voluntad")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Weapons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Messages.Database.Entities.GearItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("GearItems");
                });

            modelBuilder.Entity("Messages.Database.Entities.GlobalNpcEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Agilidad")
                        .HasColumnType("integer");

                    b.Property<string>("Apariencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArmasLigeras")
                        .HasColumnType("integer");

                    b.Property<int>("ArmasPesadas")
                        .HasColumnType("integer");

                    b.Property<string>("Ascendencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Atletismo")
                        .HasColumnType("integer");

                    b.Property<int>("Conocimiento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deduccion")
                        .HasColumnType("integer");

                    b.Property<int>("Discernimiento")
                        .HasColumnType("integer");

                    b.Property<int>("Disciplina")
                        .HasColumnType("integer");

                    b.Property<int>("Engano")
                        .HasColumnType("integer");

                    b.Property<int>("Fuerza")
                        .HasColumnType("integer");

                    b.Property<int>("Hurto")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Intelecto")
                        .HasColumnType("integer");

                    b.Property<int>("Intimidacion")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Liderazgo")
                        .HasColumnType("integer");

                    b.Property<int>("Manufactura")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConcentration")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxInvestiture")
                        .HasColumnType("integer");

                    b.Property<int>("Medicina")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Percepcion")
                        .HasColumnType("integer");

                    b.Property<int>("Perspicacia")
                        .HasColumnType("integer");

                    b.Property<int>("Persuasion")
                        .HasColumnType("integer");

                    b.Property<int>("Presencia")
                        .HasColumnType("integer");

                    b.Property<int>("Sigilo")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Supervivencia")
                        .HasColumnType("integer");

                    b.Property<string>("Talentos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Velocidad")
                        .HasColumnType("integer");

                    b.Property<int>("Voluntad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GlobalNpcs");
                });

            modelBuilder.Entity("Messages.Database.Entities.NoteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Messages.Database.Entities.SessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Messages.Database.Entities.SideQuestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<List<string>>("Acts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Benefits")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Rewards")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("Started")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("SideQuests");
                });

            modelBuilder.Entity("Messages.Database.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Messages.Database.Entities.WeaponCatalogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DamageDiceCount")
                        .HasColumnType("integer");

                    b.Property<int>("DamageDiceValue")
                        .HasColumnType("integer");

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("ExpertTraitIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RangeId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("TraitIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("WeaponTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeaponCatalog");
                });

            modelBuilder.Entity("Messages.Database.Entities.CampaignEntity", b =>
                {
                    b.HasOne("Messages.Database.Entities.UserEntity", "GmUser")
                        .WithMany()
                        .HasForeignKey("GmUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GmUser");
                });

            modelBuilder.Entity("Messages.Database.Entities.CampaignMemberEntity", b =>
                {
                    b.HasOne("Messages.Database.Entities.CampaignEntity", "Campaign")
                        .WithMany("Members")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Messages.Database.Entities.UserEntity", "User")
                        .WithMany("CampaignMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messages.Database.Entities.CharacterEntity", b =>
                {
                    b.HasOne("Messages.Database.Entities.CampaignEntity", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Messages.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Messages.Database.Entities.NoteEntity", b =>
                {
                    b.HasOne("Messages.Database.Entities.CampaignEntity", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Messages.Database.Entities.UserEntity", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Messages.Database.Entities.UserEntity", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Messages.Database.Entities.SessionEntity", b =>
                {
                    b.HasOne("Messages.Database.Entities.CampaignEntity", "Campaign")
                        .WithMany("Sessions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Messages.Database.Entities.SideQuestEntity", b =>
                {
                    b.HasOne("Messages.Database.Entities.CampaignEntity", "Campaign")
                        .WithMany("SideQuests")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Messages.Database.Entities.CampaignEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Members");

                    b.Navigation("Sessions");

                    b.Navigation("SideQuests");
                });

            modelBuilder.Entity("Messages.Database.Entities.UserEntity", b =>
                {
                    b.Navigation("CampaignMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
