namespace Messages.Database.Entities;

public class DiceRollEntity
{
    public long Id { get; set; }
    public long CampaignId { get; set; }
    public long UserId { get; set; }
    public string UserDisplayName { get; set; } = string.Empty;

    /// <summary>skill | damage | recovery | contested | free</summary>
    public string RollType { get; set; } = string.Empty;

    /// <summary>Full JSON of the roll result (AnyRollResult serialized from frontend)</summary>
    public string RollData { get; set; } = "{}";

    /// <summary>Short human-readable summary generated by the frontend</summary>
    public string RollLabel { get; set; } = string.Empty;

    /// <summary>Name of the character being rolled for (null = rolling as the user themselves)</summary>
    public string? CharacterName { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public CampaignEntity Campaign { get; set; } = null!;
}
